# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Coverage status checks
  status:
    project:
      default:
        # Target 70% coverage (current baseline ~18%)
        target: 70%
        # Allow coverage to drop by 2% without failing
        threshold: 2%
        # Only check coverage on files changed in PR
        if_ci_failed: error
    patch:
      default:
        # New code should have at least 50% coverage
        target: 50%
        threshold: 5%

  # Coverage precision (2 decimal places)
  precision: 2
  round: down
  range: "50...100"

# Comment settings for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Ignore certain paths from coverage
ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "**/__init__.py"

# Flag management
flags:
  unittests:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - src/
    carryforward: true
    # Integration tests run less frequently (only on merge)
    # so carry forward previous results
