# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Coverage status checks
  status:
    project:
      default:
        # Target 70% coverage (realistic for LLM-heavy codebase)
        target: 70%
        # Allow coverage to drop by 2% without failing
        threshold: 2%
        if_ci_failed: error
        # Only report status after all flags are uploaded
        flags:
          - unittests
          - integration
    patch:
      default:
        # New code should have coverage, but be lenient
        # Many changes are config/frontend that don't need tests
        target: 50%
        threshold: 10%
        # Only apply to src/ files
        only_pulls: true

  # Coverage precision (2 decimal places)
  precision: 2
  round: down
  # Highlight files below 60% as critical
  range: "60...100"

# Comment settings for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Ignore certain paths from coverage
ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "**/__init__.py"
  - "src/scripts/**/*"

# Flag management
flags:
  unittests:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - src/
    carryforward: true
    # Integration tests run less frequently (only on merge with src changes)
    # Carry forward ensures previous results are used when skipped
